user: deploy
repository:
deploy_to:
backup:
branch:
remote_cache: true
scm: git
releases: true
revision: true
key_path:
key_path_deployed: false
app: 93.184.216.34    #necessary to provide app otherwise whole site deletes... escalate to developers
db: 93.184.216.34     #necessary to provide db otherwise whole site deletes... escalate to developers

# If your app uses a database uncomment this:
database:
  name: sites_example
  user: deploy
  password: password
  host: 127.0.0.1
  charset: utf8
  
