user: deploy
repository:
deploy_to:
backup:
branch:
remote_cache: true
scm: git
releases: 5
revision: true
key_path:
key_path_deployed: false
password:
app: #necessary to provide app otherwise whole site deletes... escalate to developers
db: #necessary to provide db otherwise whole site deletes... escalate to developers

# If your app uses a database uncomment this:
database:
  name: sites_example
  user: deploy
  password:
  host: 127.0.0.1
  charset: utf8
  
